// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model.enums;

public enum Role {
	User,
	Admin,
	Medic;
}
