// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model.enums;

public enum VisitType {
	Baseline,
	Trattamento,
	Controllo;
}
