// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
package IngDelSw.nicoli.model;
/************************************************************/
/**
 * 
 */
public class BaselineVisit extends Visit {
}
