// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;

import IngDelSw.nicoli.model.enums.Gender;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 
 */
@Entity
@Table(name = "localization")
public class Localization {

	/**
	 * 
	 */
	@Column(name = "name")
	private String name;
	/**
	 * 
	 */
	@Id
	@Column(name = "localization_id")
	private int localization_id;
	/**
	 * 
	 */
	@Column (name = "gender")
	private Gender gender;
	/**
	 * 
	 */
	@Column(name = "description")
	private String description;
	/**
	 * 
	 */

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getLocalization_id() {
		return localization_id;
	}

	public void setLocalization_id(int localization_id) {
		this.localization_id = localization_id;
	}

	public Gender getGender() {
		return gender;
	}

	public void setGender(Gender gender) {
		this.gender = gender;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


}
