// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;
import java.time.LocalDate;
/**
 * 
 */
public class Patient extends User {
	/**
	 * 
	 */
	private int created_by;
	/**
	 * 
	 */
	private LocalDate date_of_birth;
	/**
	 * 
	 */
	private String ethnicity;
	/**
	 * 
	 */
	private String previous_history;
	/**
	 * 
	 */
	private Visit[] visit;

	/**
	 * GETTERS AND SETTERS
	 */
	public int getCreated_by() {
		return created_by;
	}

	public void setCreated_by(int created_by) {
		this.created_by = created_by;
	}

	public LocalDate getDate_of_birth() {
		return date_of_birth;
	}

	public void setDate_of_birth(LocalDate date_of_birth) {
		this.date_of_birth = date_of_birth;
	}

	public String getEthnicity() {
		return ethnicity;
	}

	public void setEthnicity(String ethnicity) {
		this.ethnicity = ethnicity;
	}

	public String getPrevious_history() {
		return previous_history;
	}

	public void setPrevious_history(String previous_history) {
		this.previous_history = previous_history;
	}

	public Visit[] getVisit() {
		return visit;
	}

	public void setVisit(Visit[] visit) {
		this.visit = visit;
	}
}
