// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;
import IngDelSw.nicoli.model.enums.Gender;
import IngDelSw.nicoli.model.enums.Role;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 *
 */
@Entity
public class Patient extends User {

	@Column(name = "created_by")
	private Integer createdBy;
	@Column(name = "date_of_birth")
	private LocalDate dateOfBirth;
	@Column(name = "ethnicity")
	private String ethnicity;
	@Column(name = "previous_history")
	private String previousHistory;

	public Patient() {

	}

	public Patient(String firstName, String lastName, String email, String password, Integer createdBy, LocalDate dateOfBirth, String ethnicity, String previous_history, Gender gender, Role role, LocalDateTime activated_at) {
		super(firstName, lastName, email, password, gender, role, activated_at);
		this.createdBy = createdBy;
		this.dateOfBirth = dateOfBirth;
		this.ethnicity = ethnicity;
		this.previousHistory = previous_history;
	}

	/**
	 * GETTERS AND SETTERS
	 */
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	public LocalDate getDateOfBirth() {
		return dateOfBirth;
	}

	public void setDateOfBirth(LocalDate dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getEthnicity() {
		return ethnicity;
	}

	public void setEthnicity(String ethnicity) {
		this.ethnicity = ethnicity;
	}

	public String getPreviousHistory() {
		return previousHistory;
	}

	public void setPreviousHistory(String previous_history) {
		this.previousHistory = previous_history;
	}

}
