// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 
 */
@Entity
@Table (name = "products_visits")
public class ProductsVisits {
	@Id
	@Column(name = "id")
	private int id;
	/**
	 * 
	 */
	@Column(name = "visit_id")
	private int visit_id;
	/**
	 * 
	 */
	@Column(name = "product_id")
	private int product_id;

	/**
	 * GETTERS AND SETTERS
	 */
	public int getVisit_id() {
		return visit_id;
	}

	public void setVisit_id(int visit_id) {
		this.visit_id = visit_id;
	}

	public int getProduct_id() {
		return product_id;
	}

	public void setProduct_id(int product_id) {
		this.product_id = product_id;
	}
}
