// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;
/**
 * 
 */
public class TreatmentVisit extends Visit{
	/**
	 * 
	 */

	/**
	 *
	 */
	public void products() {
	}

	/**
	 * GETTERS AND SETTERS
	 */


}
