// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;

import jakarta.persistence.*;



@Entity
@Table(name = "treatments")
public class Treatment {

	public Treatment() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Column(name = "patient_id")
	private Integer patientId;

	@Column(name = "motivation_title")
	private String motivationTitle;

	@Column(name = "motivation_desc")
	private String motivationDesc;

	@Column(name = "localization_id")
	private Integer localizationId;

	@Column(name = "last_visit_id")
	private Integer last_visit_id;

	public void visits() {
	}

	/**
	 * GETTERS AND SETTERS
	 */

	public Integer getId() {
		return id;}

	public void setId(Integer id) {this.id = id;}

	public Integer getPatientId() {
		return patientId;
	}

	public void setPatientId(Integer patient_id) {
		this.patientId = patient_id;
	}

	public String getMotivationTitle() {
		return motivationTitle;
	}

	public void setMotivationTitle(String motivation_title) {
		this.motivationTitle = motivation_title;
	}

	public String getMotivationDesc() {
		return motivationDesc;
	}

	public void setMotivationDesc(String motivation_desc) {
		this.motivationDesc = motivation_desc;
	}

	public Integer getLocalizationId() {
		return localizationId;
	}

	public void setLocalizationId(Integer localization_id) {
		this.localizationId = localization_id;
	}

	public Integer getLast_visit_id() {
		return last_visit_id;
	}

	public void setLast_visit_id(Integer last_visit_id) {
		this.last_visit_id = last_visit_id;
	}
}
