// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package IngDelSw.nicoli.model;
/************************************************************/

import IngDelSw.nicoli.model.enums.Gender;
import IngDelSw.nicoli.model.enums.Role;

import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Id;

@Entity
@Table (name = "users")
/**
 *
 */
public class User {
	/**
	 * 
	 */
	@Id
	@Column(name = "id")
	private int id;
	/**
	 * 
	 */
	@Column(name = "first_name")
	private String first_name;
	/**
	 *
	 */
	@Column(name = "last_name")
	private String last_name;
	/**
	 *
	 */
	@Column(name = "gender")
	private Gender gender;
	/**
	 * 
	 */

	@Column(name = "role")
	private Role role;
	/**
	 * 
	 */
	@Column(name = "activated_at")
	private LocalDateTime activated_at;

	/**
	 * @param role
	 */
	public void hasRole(Role role) {
	}

	/**
	 * 
	 */
	public void isAdmin() {
	}

	/**
	 * 
	 */
	public void isUser() {
	}

	/**
	 * 
	 */
	public void isMedic() {
	}

}
