// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
package IngDelSw.nicoli.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.time.LocalDate;

/**
 * 
 */
@Entity
@Table(name = "visit")
public abstract class Visit {
	@Id
	private int id;
	/**
	 * 
	 */
	@Column(name = "patient_id")
	private int patient_id;
	/**
	 * 
	 */
	@Column(name = "treatment_id")
	private int treatment_id;
	/**
	 * 
	 */
	@Column(name = "medic_id")
	private int medic_id;
	/**
	 * 
	 */
	@Column(name = "date")
	private LocalDate date;
	/**
	 * 
	 */
	@Column(name = "localization_id")
	private int localization_id;
	/**
	 * 
	 */
	@Column(name = "notes")
	private String notes;
	/**
	 * 
	 */
	@Column(name = "visit_id")
	private int visit_id;
	/**
	 * 
	 */

	/**
	 * 
	 */
	public void treatment() {
	}

	/**
	 * 
	 */
	public void localization() {
	}

	/**
	 * 
	 */
	public void photos() {
	}
}
